# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.BigIntegerField(verbose_name='订单号')),
                ('trade_parent_id', models.BigIntegerField(verbose_name='父订单号')),
                ('num_iid', models.BigIntegerField(verbose_name='商品ID')),
                ('item_title', models.CharField(max_length=1000, verbose_name='商品标题')),
                ('item_num', models.BigIntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='单价')),
                ('remark', models.CharField(default='', max_length=1000, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单子表',
                'verbose_name_plural': '订单子表',
            },
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_parent_id', models.BigIntegerField(verbose_name='父订单号')),
                ('batch_id', models.BigIntegerField(verbose_name='批次号')),
                ('total_price', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='总金额')),
                ('pay_price', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(db_index=True, null=True, verbose_name='订单付款时间')),
                ('pay_account', models.CharField(default='', max_length=100, verbose_name='付款账号')),
                ('pay_channel', models.CharField(default='wechat', help_text='alipay, wechat, other', max_length=20, verbose_name='支付渠道')),
                ('status', models.CharField(default='unpaid', help_text='paied, unpaid, cancel, settled', max_length=20, verbose_name='订单状态')),
                ('buyer_id', models.BigIntegerField(verbose_name='下单用户')),
                ('seller_id', models.BigIntegerField(verbose_name='卖家')),
                ('buyer_remark', models.CharField(default='', max_length=1000, verbose_name='买家备注')),
                ('seller_remark', models.CharField(default='', max_length=1000, verbose_name='卖家备注')),
                ('spread_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='推广者')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='推广者获得的佣金金额')),
                ('address_id', models.BigIntegerField(blank=True, null=True, verbose_name='收货地址')),
                ('activity_id', models.BigIntegerField(blank=True, null=True, verbose_name='活动')),
                ('activity_name', models.CharField(default='', max_length=1000, verbose_name='活动名称')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='推广者获得的佣金比例')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.06, max_digits=20, max_length=100, verbose_name='推广者获得的佣金比例')),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=20, max_length=100, verbose_name='卖家收益')),
                ('earning_time', models.DateTimeField(db_index=True, null=True, verbose_name='订单结算时间')),
                ('remark', models.CharField(default='', max_length=1000, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单主表',
                'verbose_name_plural': '订单主表',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户')),
                ('money', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='金额')),
                ('account_type', models.IntegerField(default=0, verbose_name='账户类型')),
                ('type', models.IntegerField(default=0, verbose_name='类型收入或者指出')),
                ('desc', models.CharField(default='', max_length=1000, verbose_name='描述')),
                ('desc1', models.CharField(default='', max_length=1000, verbose_name='描述1')),
                ('desc2', models.CharField(default='', max_length=1000, verbose_name='描述2')),
                ('desc3', models.CharField(default='', max_length=1000, verbose_name='描述3')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户流水表',
                'verbose_name_plural': '用户流水表',
            },
        ),
        migrations.CreateModel(
            name='WithdrawCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户')),
                ('user_name', models.CharField(default='', max_length=50, verbose_name='支付宝姓名')),
                ('money', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='体现金额')),
                ('status', models.IntegerField(choices=[(0, '申请提现中'), (1, '体现陈功'), (2, '体现失败')], default=0, verbose_name='状态0申请体现中，1体现成功，2体现失败')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('alipay_account', models.CharField(max_length=50, verbose_name='支付宝账号')),
                ('order_num', models.CharField(blank=True, default='', max_length=50, verbose_name='流水号')),
                ('remark', models.CharField(blank=True, default='', max_length=50, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提现申请表',
                'verbose_name_plural': '提现申请表',
            },
        ),
    ]
