# Generated by Django 2.0.6 on 2018-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180627_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='is_reward',
            field=models.IntegerField(default=0, verbose_name='是否获取奖励'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.006, max_digits=20, max_length=100, verbose_name='推广者获得的佣金比例'),
        ),
    ]
