# Generated by Django 2.0.6 on 2018-07-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_withdrawcash_payment_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeAssert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='money')),
                ('reason', models.CharField(default='REFUND', max_length=150, verbose_name='原因')),
                ('type', models.CharField(default='refund', max_length=50, verbose_name='冻结类型')),
                ('relation_id', models.CharField(default='', max_length=150, verbose_name='关联ID')),
                ('status', models.CharField(default='freeze', max_length=50, verbose_name='冻结状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产冻结信息',
                'verbose_name_plural': '资产冻结信息',
            },
        ),
    ]
