# Generated by Django 2.0.6 on 2018-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_freezeassert'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='apply_refund_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='订单申请退款时间'),
        ),
    ]
