# Generated by Django 2.0.6 on 2018-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderuser_apply_refund_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='trade_parent_id',
            field=models.BigIntegerField(db_index=True, verbose_name='父订单号'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='activity_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='buyer_id',
            field=models.BigIntegerField(db_index=True, verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='seller_id',
            field=models.BigIntegerField(db_index=True, verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='trade_parent_id',
            field=models.BigIntegerField(db_index=True, verbose_name='父订单号'),
        ),
    ]
