# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=150, verbose_name='交易订单号')),
                ('user_id', models.BigIntegerField(verbose_name='支付用户')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='交易价格')),
                ('openid', models.CharField(max_length=150, verbose_name='openid')),
                ('prepay_id', models.CharField(default='', max_length=150, verbose_name='prepay_id')),
                ('result_code', models.CharField(default='', max_length=150, verbose_name='result_code')),
                ('return_code', models.CharField(default='', max_length=150, verbose_name='return_code')),
                ('err_code', models.CharField(default='', max_length=150, verbose_name='err_code')),
                ('transaction_id', models.CharField(default='', max_length=150, verbose_name='微信订单号')),
                ('time_end', models.CharField(default='', max_length=150, verbose_name='交易完成时间')),
                ('total_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='订单金额')),
                ('trade_state', models.CharField(default='', max_length=150, verbose_name='订单状态')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信支付信息',
                'verbose_name_plural': '微信支付信息',
            },
        ),
    ]
