# Generated by Django 2.0.6 on 2018-06-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatpay',
            name='order_id',
            field=models.CharField(default='', max_length=150, verbose_name='订单号'),
        ),
    ]
