# Generated by Django 2.0.6 on 2018-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_wechatpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_refund_no', models.CharField(max_length=150, verbose_name='交易订单号')),
                ('order_id', models.CharField(default='', max_length=150, verbose_name='订单号')),
                ('user_id', models.BigIntegerField(verbose_name='支付用户')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='交易价格')),
                ('result_code', models.CharField(default='', max_length=150, verbose_name='result_code')),
                ('return_code', models.CharField(default='', max_length=150, verbose_name='return_code')),
                ('err_code', models.CharField(default='', max_length=150, verbose_name='err_code')),
                ('transaction_id', models.CharField(default='', max_length=150, verbose_name='微信订单号')),
                ('refund_id', models.CharField(default='', max_length=150, verbose_name='退款单号')),
                ('success_time', models.CharField(default='', max_length=150, verbose_name='交易完成时间')),
                ('total_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='标价金额')),
                ('refund_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='申请退款金额')),
                ('settlement_refund_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='退款金额')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='退款成功时间')),
                ('refund_recv_accout', models.CharField(default='', max_length=150, verbose_name='refund_recv_accout')),
                ('refund_account', models.CharField(default='', max_length=150, verbose_name='refund_account')),
                ('refund_request_source', models.CharField(default='', max_length=150, verbose_name='refund_request_source')),
                ('out_trade_no', models.CharField(default='', max_length=150, verbose_name='out_trade_no')),
                ('refund_status', models.CharField(default='', max_length=150, verbose_name='refund_status')),
                ('refund_state', models.CharField(default='', max_length=150, verbose_name='refund_state')),
                ('reason', models.CharField(default='', max_length=150, verbose_name='退款原因')),
                ('fail_reason', models.CharField(default='', max_length=150, verbose_name='退款失败原因')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信退款信息',
                'verbose_name_plural': '微信退款信息',
            },
        ),
    ]
