# Generated by Django 2.0.6 on 2018-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeURLParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_param', models.CharField(blank=True, max_length=500, null=True, verbose_name='url的参数')),
                ('url_path', models.CharField(max_length=255, verbose_name='小程序页面地址')),
                ('md5_key', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='urlpath和query_param生成的md5')),
                ('qr_code_url', models.URLField(blank=True, default='', verbose_name='二维码地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '二维码url参数表',
                'verbose_name_plural': '二维码url参数表',
            },
        ),
    ]
