# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JieLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('description', models.TextField(blank=True, default='', max_length=4000, null=True, verbose_name='活动描述（推荐理由）')),
                ('image_url', models.ImageField(blank=True, default='', help_text='商品主图', max_length=1000, upload_to='', verbose_name='商品主图')),
                ('begin_time', models.DateTimeField(db_index=True, verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='活动结束时间')),
                ('status', models.IntegerField(choices=[(0, '上架'), (1, '下架')], db_index=True, default=0, verbose_name='状态')),
                ('small_images', models.TextField(default='', max_length=4000, verbose_name='小图（空格分割）')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='佣金比率(%)')),
                ('wechat_no', models.CharField(max_length=50, verbose_name='微信号')),
                ('is_logistics', models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='是否需要物流配置')),
                ('browse_num', models.BigIntegerField(default=0, verbose_name='活动浏览量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('passport_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.PassportUser')),
            ],
        ),
        migrations.CreateModel(
            name='JielongProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.IntegerField(choices=[(0, '是'), (1, '否')], db_index=True, default=0, verbose_name='是否有效')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('jielong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.JieLong')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
