# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('zk_final_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='在售价')),
                ('volume', models.BigIntegerField(verbose_name='销量')),
                ('description', models.TextField(blank=True, default='', max_length=4000, null=True, verbose_name='宝贝描述（推荐理由）')),
                ('sku_desc', models.CharField(max_length=200, verbose_name='规格描述')),
                ('sku_num', models.BigIntegerField(default=0, verbose_name='商品库存量')),
                ('max_buy_limit', models.BigIntegerField(default=10, verbose_name='商品购买数量限制')),
                ('image_url', models.ImageField(blank=True, default='', help_text='商品主图', max_length=1000, upload_to='', verbose_name='商品主图')),
                ('small_images', models.TextField(default='', max_length=4000, verbose_name='小图（空格分割）')),
                ('video_url', models.CharField(max_length=300, verbose_name='视频地址')),
                ('status', models.IntegerField(choices=[(0, '上架'), (1, '下架')], db_index=True, default=0, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
