# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登陆时间')),
            ],
            options={
                'verbose_name': '基础用户',
                'verbose_name_plural': '基础用户',
            },
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(blank=True, max_length=64, null=True, verbose_name='unionid')),
                ('openid', models.CharField(max_length=64, verbose_name='openid')),
                ('session_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='微信session_key')),
                ('nickname', models.CharField(max_length=128, null=True, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='头像')),
                ('refresh_token', models.CharField(max_length=256, verbose_name='refresh_token, 30天有效期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('passport_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passport.PassportUser')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
    ]
