# Generated by Django 2.0.6 on 2018-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=128, unique=True, verbose_name='session key'),
        ),
    ]
