# Generated by Django 2.0.6 on 2018-07-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippoconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfig',
            name='product_code',
            field=models.CharField(db_index=True, help_text='全部小写字母，可以使用下划线', max_length=256, verbose_name='应用代码'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='type',
            field=models.IntegerField(choices=[(10, '10-系统错误'), (20, '20-用户账号类错误'), (30, '30-商品类错误'), (40, '40-微信系统错误'), (50, '50-外部系统错误'), (90, '90-其它')], help_text='错误代码的前两位和错误类别代码要一致', verbose_name='错误类别'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='platform_code',
            field=models.CharField(db_index=True, help_text='全部小写字母，可以使用下划线', max_length=256, verbose_name='平台代码'),
        ),
    ]
