# Generated by Django 2.0.6 on 2018-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户')),
                ('mobile', models.CharField(max_length=150, verbose_name='收货人电话')),
                ('postal_code', models.CharField(max_length=150, verbose_name='邮编')),
                ('name', models.CharField(max_length=150, verbose_name='收货人姓名')),
                ('province', models.CharField(max_length=150, verbose_name='国际收货一级地址')),
                ('country', models.CharField(max_length=150, verbose_name='国际收货二级地址家')),
                ('city', models.CharField(max_length=150, verbose_name='国际收货三级地址')),
                ('address_detail', models.CharField(max_length=500, verbose_name='收货地址详情')),
                ('national_code', models.CharField(max_length=500, verbose_name='国际编码 ')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='JieLongSpreadUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_sponsor_id', models.BigIntegerField(verbose_name='邀请推广用户id')),
                ('status', models.IntegerField(choices=[(0, '申请中'), (1, '同意申请'), (2, '拒绝申请'), (3, '取消推广人')], db_index=True, default=0, verbose_name='推广人状态')),
                ('apply_reason', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='申请理由 ')),
                ('wechat_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='微信号 ')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('passport_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.PassportUser', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '推广人用户关系表',
                'verbose_name_plural': '推广人用户关系表',
            },
        ),
        migrations.CreateModel(
            name='JieLongUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attention', models.IntegerField(choices=[(0, '关注'), (1, '未关注')], db_index=True, default=0, verbose_name='是否关注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('jielong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.JieLong', verbose_name='接龙活动')),
                ('passport_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.PassportUser', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '接龙参与用户关系表',
                'verbose_name_plural': '接龙参与用户关系表',
            },
        ),
        migrations.CreateModel(
            name='ShareUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_user_id', models.BigIntegerField(verbose_name='分享用户id')),
                ('share_user_role', models.IntegerField(choices=[(0, '普通用户'), (1, '推广人')], default=0, verbose_name='分享用户身份')),
                ('browse_num', models.BigIntegerField(default=0, verbose_name='活动浏览量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('browse_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.PassportUser', verbose_name='浏览用户')),
                ('jielong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.JieLong', verbose_name='接龙活动')),
            ],
            options={
                'verbose_name': '分享用户关系表',
                'verbose_name_plural': '分享用户关系表',
            },
        ),
    ]
